joy_node:
  ros__parameters:
    device_id: 0
    device_name: "Xbox 360 Controller"
    deadzone: 0.05
    publish_rate: 100.0


teleop_node:
  ros__parameters:
    axis_linear:
      x: 7  # Left stick vertical (axis 7)
    scale_linear:
      x: 1.0
    scale_linear_turbo:
      x: 2.0

    axis_angular:
      yaw: 6  # Left stick horizontal (axis 6)
    scale_angular:
      yaw: 1.0
    scale_angular_turbo:
      yaw: 2.0

    enable_button: 5  # RB button on Xbox 360
    enable_turbo_button: 4  # LB on Xbox 360
    require_enable_button: true
